applications:
  - name: ${app_name}
    namespace: ${app_namespace}
    project: default
    source:
      repoURL: ${helm_repo_url}
      path: ${helm_chart_path}
      targetRevision: main
      helm:
        valueFiles:
          - values.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: ${app_namespace}
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

repositories:
  - name: ${app_name}
    url: ${helm_repo_url}
    username: ${github_username}
    password: ${github_token}

repoConfig:
  insecure: "true"
  enableLfs: "true"
